#INITIAL SETTINGS
eval_metric: ["logloss", "auc"]

XGB_Options_Default:
  n_jobs: -1 #"cpu_count() // 2"
  cv: 3
  scoring: "recall"  #'f1_macro','roc_auc_ovr'
  seed: 42
  max_depth: [6,9,12]
  min_child_weight: [4] #[1, 4, 7]
  n_estimators: [100]
  gamma: [0, 0.2, 0.4]
  colsample_bytree: [0.5, 0.75, 0.9]
  subsample: [0.9, 1.0]
  reg_alpha: [1e-6, 1, 10]
  reg_lambda: [1e-6, 1, 10]
  learning_rate: [0.1, 0.2, 0.3]
  scale_pos_weight: [1, 3, 5]
  verbose: 1


XGB_Options:
  n_jobs: -1 #"cpu_count() // 2"
  cv: 3
  scoring: "recall"  #'f1_macro','roc_auc_ovr'
  seed: 42
  max_depth: [9] #[9, 12,15]
  min_child_weight: [4] #[1, 4, 7]
  n_estimators: [100]
  gamma: [0.7] #[0.5, 0.6, 0.7]
  colsample_bytree: [0.2] #[0.2, 0.3, 0.4]
  subsample: [0.9] #[0.8, 1.0]
  reg_alpha: [10] #[1e-6, 1, 10]
  reg_lambda: [30] #[15, 20, 30] #[1e-6, 1, 10]
  learning_rate: [0.1] #[0.1, 0.2, 0.3]
  scale_pos_weight: [11] #[7, 9, 11] # [1, 3, 5]
  verbose: 1

XGB_Options_best_recall:
  n_jobs: -1 #"cpu_count() // 2"
  cv: 3
  scoring: "accuracy"
  seed: 42
  max_depth: 9
  min_child_weight: 4
  n_estimators: 100
  gamma: 0.7
  colsample_bytree: 0.2 
  subsample: 0.9
  reg_alpha: 1e-6
  reg_lambda: 30
  learning_rate: 0.1
  scale_pos_weight: 11
  verbose: 1

XGB_Options_best_roc_auc:
  n_jobs: -1 #"cpu_count() // 2"
  cv: 3
  scoring: "accuracy"
  seed: 42
  max_depth: 5
  min_child_weight: 2
  n_estimators: 125
  gamma: 0.95
  colsample_bytree: 0.6 
  subsample: 0.8
  reg_alpha: 0.001
  reg_lambda: 18
  learning_rate: 0.05
  scale_pos_weight: 6
  verbose: 1

XGB_Baseline:
  learning_rate: 0.3
  n_estimators: 100
  seed: 42
  subsample: 0.9
  colsample_bytree: 1
  eval_metric: ["logloss", "auc"]
  max_depth: 12
  gamma: 0.2
  min_child_weight: 1

XGB_Dmat:
  learning_rate: 0.3 # also called eta in xgboost
  max_depth: 12  # the maximum depth of each tree
  subsample: 0.9
  colsample_bytree: 0.5
  gamma: 0.2
  min_child_weight: 1
  silent: 1  # logging mode - quiet
  objective: "binary:hinge" #logistic"
  num_class: 1
  eval_metric: "logloss"  # the number of classes that exist in this datset
  #scale_pos_weight: 3
  reg_lambda: 10